'use client';
import { useState } from 'react';
import { sources, parseCsv, normalize, type Source, type Mapping, type Transaction } from '@/lib/imports';
import { useLedger } from '@/lib/store';
export default function ImportPage(){
 const {transactions,save,ready,error:storageError}=useLedger();
 const [source,setSource]=useState<Source>('Bank'); const [account,setAccount]=useState('');
 const [headers,setHeaders]=useState<string[]>([]); const [rows,setRows]=useState<Record<string,string>[]>([]);
 const [mapping,setMapping]=useState<Mapping>({date:'',description:'',amount:''});
 const [preview,setPreview]=useState<Transaction[]>([]); const [error,setError]=useState(''); const [notice,setNotice]=useState('');
 function clear(){setPreview([]);setNotice('');}
 async function read(file?:File){clear();setError('');setHeaders([]);setRows([]); if(!file)return;try{if(file.size>5*1024*1024)throw new Error('Use CSV files under 5 MB');const parsed=parseCsv(await file.text());setHeaders(parsed.headers);setRows(parsed.rows);setMapping({date:'',description:'',amount:''});}catch(e){setError((e as Error).message);}}
 const field=(key:keyof Mapping,label:string)=><label>{label}<select value={String(mapping[key]||'')} onChange={e=>{setMapping({...mapping,[key]:e.target.value});clear();}}><option value="">Select column</option>{headers.map(h=><option key={h}>{h}</option>)}</select></label>;
 return <><h1>Import transactions</h1><p>Choose your export source, then map its columns. Formats vary; verify dates, signs, currency, fees and transfers in the preview.</p><section><label>Source<select value={source} onChange={e=>{setSource(e.target.value as Source);clear();}}>{sources.map(s=><option key={s}>{s}</option>)}</select></label><label>Account name<input value={account} onChange={e=>{setAccount(e.target.value);clear();}} placeholder="Square Banking / operating"/></label><label>CSV file<input type="file" accept=".csv,text/csv" onChange={e=>void read(e.target.files?.[0])}/></label>{headers.length>0 && <><div className="grid">{field('date','Date (ISO or US)')}{field('description','Description')}{field('amount','Signed amount')}{field('debit','Debit (if no amount)')}{field('credit','Credit (if no amount)')}{field('currency','Currency (default USD)')}{field('id','Provider transaction ID (recommended)')}</div><label><input type="checkbox" checked={!!mapping.positiveIsExpense} onChange={e=>{setMapping({...mapping,positiveIsExpense:e.target.checked});clear();}}/>Positive signed amounts are expenses (some card exports)</label><button disabled={!mapping.date||!mapping.description||(!mapping.amount&&(!mapping.debit||!mapping.credit))} onClick={()=>{try{const data=normalize(rows,mapping,source,account);setPreview(data);setError('');}catch(e){setPreview([]);setError((e as Error).message);}}}>Preview normalization</button></>}{(error||storageError)&&<p className="error">{error||storageError}</p>}{notice&&<p>{notice}</p>}</section>{preview.length>0&&<section><h2>Preview · {preview.length} rows</h2><p>Negative = money out; positive = money in. Every saved row enters review. Repeated identities are skipped; identical purchases without provider IDs can collide.</p><div className="scroll"><table><thead><tr><th>Date</th><th>Description</th><th>Amount</th><th>Suggestion</th></tr></thead><tbody>{preview.slice(0,100).map((t,i)=><tr key={i}><td>{t.date}</td><td>{t.description}</td><td>{(t.amountCents/100).toFixed(2)} {t.currency}</td><td>{t.category} / {t.kind}</td></tr>)}</tbody></table></div><button disabled={!ready} onClick={()=>{const ids=new Set(transactions.map(t=>t.id));const fresh=preview.filter(t=>{if(ids.has(t.id))return false;ids.add(t.id);return true;});save([...transactions,...fresh]);setNotice(fresh.length+' new rows; '+(preview.length-fresh.length)+' duplicate identities skipped. Check storage errors before leaving.');setPreview([]);}}>Save to local review queue</button></section>}</>;
}
