-- Apply once in Supabase SQL Editor or with migrations.
begin;
create table public.accounts (id uuid primary key default gen_random_uuid(), owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade, created_at timestamptz not null default now(), name text not null, provider text not null, account_type text not null check (account_type in ('bank','card','payment_processor','cash')), currency text not null default 'USD' check (currency ~ '^[A-Z]{3}$'), unique (id,owner_id));
alter table public.accounts enable row level security;
create policy owner_access on public.accounts for all to authenticated using (owner_id = (select auth.uid())) with check (owner_id = (select auth.uid()));
grant select, insert, update, delete on public.accounts to authenticated;
revoke all on public.accounts from anon;
create table public.categories (id uuid primary key default gen_random_uuid(), owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade, created_at timestamptz not null default now(), name text not null, kind text not null check (kind in ('income','expense','transfer')), unique (id,owner_id));
alter table public.categories enable row level security;
create policy owner_access on public.categories for all to authenticated using (owner_id = (select auth.uid())) with check (owner_id = (select auth.uid()));
grant select, insert, update, delete on public.categories to authenticated;
revoke all on public.categories from anon;
create table public.category_rules (id uuid primary key default gen_random_uuid(), owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade, created_at timestamptz not null default now(), vendor text not null, pattern text not null, category text not null, kind text not null check (kind in ('expense','transfer')), priority integer not null default 50, enabled boolean not null default true, unique (id,owner_id));
alter table public.category_rules enable row level security;
create policy owner_access on public.category_rules for all to authenticated using (owner_id = (select auth.uid())) with check (owner_id = (select auth.uid()));
grant select, insert, update, delete on public.category_rules to authenticated;
revoke all on public.category_rules from anon;
create table public.import_batches (id uuid primary key default gen_random_uuid(), owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade, created_at timestamptz not null default now(), account_id uuid not null, source text not null, filename text not null, status text not null default 'pending' check (status in ('pending','committed','failed')), row_count integer not null default 0, unique (id,owner_id));
alter table public.import_batches enable row level security;
create policy owner_access on public.import_batches for all to authenticated using (owner_id = (select auth.uid())) with check (owner_id = (select auth.uid()));
grant select, insert, update, delete on public.import_batches to authenticated;
revoke all on public.import_batches from anon;
create table public.clients (id uuid primary key default gen_random_uuid(), owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade, created_at timestamptz not null default now(), name text not null, email text, billing_details jsonb not null default '{}'::jsonb, unique (id,owner_id));
alter table public.clients enable row level security;
create policy owner_access on public.clients for all to authenticated using (owner_id = (select auth.uid())) with check (owner_id = (select auth.uid()));
grant select, insert, update, delete on public.clients to authenticated;
revoke all on public.clients from anon;
create table public.projects (id uuid primary key default gen_random_uuid(), owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade, created_at timestamptz not null default now(), client_id uuid, name text not null, status text not null default 'active', budget_cents bigint not null default 0, unique (id,owner_id));
alter table public.projects enable row level security;
create policy owner_access on public.projects for all to authenticated using (owner_id = (select auth.uid())) with check (owner_id = (select auth.uid()));
grant select, insert, update, delete on public.projects to authenticated;
revoke all on public.projects from anon;
create table public.invoices (id uuid primary key default gen_random_uuid(), owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade, created_at timestamptz not null default now(), client_id uuid not null, project_id uuid, invoice_number text not null, status text not null default 'draft' check (status in ('draft','sent','paid','void')), currency text not null default 'USD', total_cents bigint not null default 0, due_date date, unique (owner_id,invoice_number), unique (id,owner_id));
alter table public.invoices enable row level security;
create policy owner_access on public.invoices for all to authenticated using (owner_id = (select auth.uid())) with check (owner_id = (select auth.uid()));
grant select, insert, update, delete on public.invoices to authenticated;
revoke all on public.invoices from anon;
create table public.invoice_items (id uuid primary key default gen_random_uuid(), owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade, created_at timestamptz not null default now(), invoice_id uuid not null, description text not null, quantity numeric(12,3) not null default 1 check (quantity > 0), unit_price_cents bigint not null default 0, unique (id,owner_id));
alter table public.invoice_items enable row level security;
create policy owner_access on public.invoice_items for all to authenticated using (owner_id = (select auth.uid())) with check (owner_id = (select auth.uid()));
grant select, insert, update, delete on public.invoice_items to authenticated;
revoke all on public.invoice_items from anon;
create table public.subscriptions (id uuid primary key default gen_random_uuid(), owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade, created_at timestamptz not null default now(), vendor text not null, amount_cents bigint not null, currency text not null default 'USD', cadence text not null check (cadence in ('monthly','annual','other')), next_renewal date, active boolean not null default true, unique (id,owner_id));
alter table public.subscriptions enable row level security;
create policy owner_access on public.subscriptions for all to authenticated using (owner_id = (select auth.uid())) with check (owner_id = (select auth.uid()));
grant select, insert, update, delete on public.subscriptions to authenticated;
revoke all on public.subscriptions from anon;
create table public.transactions (id uuid primary key default gen_random_uuid(), owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade, created_at timestamptz not null default now(), account_id uuid not null, import_batch_id uuid, project_id uuid, external_id text, dedupe_key text not null, occurred_on date not null, description text not null, amount_cents bigint not null, currency text not null default 'USD' check (currency ~ '^[A-Z]{3}$'), category text not null default 'Uncategorized', kind text not null check (kind in ('income','expense','transfer')), review_status text not null default 'pending' check (review_status in ('pending','approved')), matched_rule text, raw jsonb not null default '{}'::jsonb, unique (owner_id,account_id,dedupe_key), unique (id,owner_id));
alter table public.transactions enable row level security;
create policy owner_access on public.transactions for all to authenticated using (owner_id = (select auth.uid())) with check (owner_id = (select auth.uid()));
grant select, insert, update, delete on public.transactions to authenticated;
revoke all on public.transactions from anon;
alter table public.import_batches add foreign key (account_id,owner_id) references public.accounts(id,owner_id);
alter table public.projects add foreign key (client_id,owner_id) references public.clients(id,owner_id);
alter table public.invoices add foreign key (client_id,owner_id) references public.clients(id,owner_id);
alter table public.invoices add foreign key (project_id,owner_id) references public.projects(id,owner_id);
alter table public.invoice_items add foreign key (invoice_id,owner_id) references public.invoices(id,owner_id);
alter table public.transactions add foreign key (account_id,owner_id) references public.accounts(id,owner_id);
alter table public.transactions add foreign key (import_batch_id,owner_id) references public.import_batches(id,owner_id);
alter table public.transactions add foreign key (project_id,owner_id) references public.projects(id,owner_id);
create index transactions_owner_date on public.transactions(owner_id,occurred_on);
create index transactions_review on public.transactions(owner_id,review_status);
commit;
